<?php

use App\Models\Student;
use Illuminate\Database\Seeder;

class StudentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        {
            $students = [
                [
                    "surname" => "Dare",
                    "first_name" => "Koby",
                    "nationality" => "UK",
                    "email" => "Astrid@salma.com",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Dicki",
                    "first_name" => "Kelli",
                    "nationality" => "UK",
                    "email" => "Ivory@ashtyn.me",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Carter",
                    "first_name" => "Golden",
                    "nationality" => "UK",
                    "email" => "Ari@flo.tv",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Koch",
                    "first_name" => "Emory",
                    "nationality" => "UK",
                    "email" => "Gene_Hilpert@laurie.io",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Kilback",
                    "first_name" => "Marjorie",
                    "nationality" => "Dominican Republic",
                    "email" => "Antonia.Hauck@giuseppe.tv",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Hoeger",
                    "first_name" => "Ernest",
                    "nationality" => "Panama",
                    "email" => "Maritza_Mann@abelardo.tv",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Hudson",
                    "first_name" => "Rebecca",
                    "nationality" => "Chile",
                    "email" => "Reynold_Ferry@bennett.us",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Hirthe",
                    "first_name" => "Josefina",
                    "nationality" => "Kyrgyzstan",
                    "email" => "Augustine@cassie.tv",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Ebert",
                    "first_name" => "Wanda",
                    "nationality" => "Palau",
                    "email" => "Amina.Farrell@charlie.net",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Denesik",
                    "first_name" => "Burnice",
                    "nationality" => "Kuwait",
                    "email" => "Tyrese@don.ca",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Moen",
                    "first_name" => "Harold",
                    "nationality" => "Vatican City",
                    "email" => "Neil@merlin.name",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Spencer",
                    "first_name" => "Brennon",
                    "nationality" => "Cambodia",
                    "email" => "Alexandria@eva.io",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Ziemann",
                    "first_name" => "Stanley",
                    "nationality" => "Azerbaijan",
                    "email" => "Micaela@millie.info",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Rempel",
                    "first_name" => "Forest",
                    "nationality" => "Seychelles",
                    "email" => "Chyna_Nolan@elody.org",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Zboncak",
                    "first_name" => "Gregory",
                    "nationality" => "Kazakhstan",
                    "email" => "Annamae_Runte@soledad.us",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Weimann",
                    "first_name" => "Valentine",
                    "nationality" => "Turks and Caicos Islands",
                    "email" => "Jeromy_Blick@katrine.biz",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Waelchi",
                    "first_name" => "Alexandria",
                    "nationality" => "People's Democratic Republic of Yemen",
                    "email" => "Everette_Torphy@halle.biz",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Altenwerth",
                    "first_name" => "Florian",
                    "nationality" => "Wake Island",
                    "email" => "Adelbert.Ryan@francisca.org",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Zieme",
                    "first_name" => "Faye",
                    "nationality" => "Guatemala",
                    "email" => "Joannie.Brown@sigurd.co.uk",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Beatty",
                    "first_name" => "Raleigh",
                    "nationality" => "British Antarctic Territory",
                    "email" => "Alessandra_Hayes@jamal.biz",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Kuhic",
                    "first_name" => "Dolly",
                    "nationality" => "Paraguay",
                    "email" => "Sonny@golda.net",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Koepp",
                    "first_name" => "Mikel",
                    "nationality" => "Liberia",
                    "email" => "Rosella@cruz.biz",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Pfannerstill",
                    "first_name" => "May",
                    "nationality" => "Puerto Rico",
                    "email" => "Dave@carlee.me",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Douglas",
                    "first_name" => "Otho",
                    "nationality" => "Denmark",
                    "email" => "Walter@karley.biz",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Conroy",
                    "first_name" => "Napoleon",
                    "nationality" => "Afghanistan",
                    "email" => "Charley.Orn@frances.co.uk",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Doyle",
                    "first_name" => "Elza",
                    "nationality" => "Liechtenstein",
                    "email" => "Isobel@simone.biz",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Schulist",
                    "first_name" => "Maci",
                    "nationality" => "United States",
                    "email" => "Reginald.Klein@keshawn.name",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Hansen",
                    "first_name" => "Kyler",
                    "nationality" => "Canada",
                    "email" => "Lorine@rebeka.com",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Conn",
                    "first_name" => "Jean",
                    "nationality" => "Kiribati",
                    "email" => "Zackary.Dickinson@gonzalo.info",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Yost",
                    "first_name" => "Reilly",
                    "nationality" => "South Africa",
                    "email" => "Herman@avis.me",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Quigley",
                    "first_name" => "Shad",
                    "nationality" => "Bhutan",
                    "email" => "Roy@judah.com",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Quitzon",
                    "first_name" => "Beatrice",
                    "nationality" => "Timor-Leste",
                    "email" => "Jana@herta.name",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Langworth",
                    "first_name" => "Lonny",
                    "nationality" => "New Zealand",
                    "email" => "Sophia.Paucek@jamir.net",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Kiehn",
                    "first_name" => "Rosalinda",
                    "nationality" => "Dominican Republic",
                    "email" => "Gia@nestor.us",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Parker",
                    "first_name" => "Rebekah",
                    "nationality" => "Kyrgyzstan",
                    "email" => "Faustino@shane.us",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Kuhlman",
                    "first_name" => "Rhoda",
                    "nationality" => "Gibraltar",
                    "email" => "Roel@kianna.net",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Cruickshank",
                    "first_name" => "Judd",
                    "nationality" => "Macau SAR China",
                    "email" => "Bell@buddy.co.uk",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Yundt",
                    "first_name" => "Sarah",
                    "nationality" => "Papua New Guinea",
                    "email" => "Marcia@noe.org",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Pacocha",
                    "first_name" => "Russ",
                    "nationality" => "Greenland",
                    "email" => "Shakira_Kessler@moriah.co.uk",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Purdy",
                    "first_name" => "Kali",
                    "nationality" => "Mauritania",
                    "email" => "Ignatius@madison.info",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Block",
                    "first_name" => "Janick",
                    "nationality" => "Belarus",
                    "email" => "Lamont@david.info",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Waelchi",
                    "first_name" => "Ford",
                    "nationality" => "Paraguay",
                    "email" => "Marta.Grimes@malinda.org",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Batz",
                    "first_name" => "Francesca",
                    "nationality" => "Netherlands Antilles",
                    "email" => "Janie.Klocko@dallin.net",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Rogahn",
                    "first_name" => "Lukas",
                    "nationality" => "Cape Verde",
                    "email" => "Gage.Willms@ruben.me",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Funk",
                    "first_name" => "Wilhelmine",
                    "nationality" => "Zimbabwe",
                    "email" => "Daphne@darryl.biz",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Nader",
                    "first_name" => "Jude",
                    "nationality" => "Panama Canal Zone",
                    "email" => "Payton@rupert.org",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Stroman",
                    "first_name" => "Frankie",
                    "nationality" => "Saint Martin",
                    "email" => "Saul@gia.name",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Jaskolski",
                    "first_name" => "Mina",
                    "nationality" => "Bermuda",
                    "email" => "Amos_Effertz@jennie.info",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Zieme",
                    "first_name" => "Mack",
                    "nationality" => "Uzbekistan",
                    "email" => "Martin@isabelle.com",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Tromp",
                    "first_name" => "Celestine",
                    "nationality" => "Peru",
                    "email" => "Loy@evalyn.us",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Nitzsche",
                    "first_name" => "Zella",
                    "nationality" => "New Zealand",
                    "email" => "Bridgette@gordon.us",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Kuphal",
                    "first_name" => "Ila",
                    "nationality" => "Maldives",
                    "email" => "Terrance.Rowe@mario.co.uk",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Cruickshank",
                    "first_name" => "Eda",
                    "nationality" => "Jamaica",
                    "email" => "Abelardo@elza.ca",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Koepp",
                    "first_name" => "Jaylen",
                    "nationality" => "Monaco",
                    "email" => "Norbert@kristian.io",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Kohler",
                    "first_name" => "Kristina",
                    "nationality" => "Russia",
                    "email" => "Aidan@nona.name",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Ondricka",
                    "first_name" => "Sean",
                    "nationality" => "Turks and Caicos Islands",
                    "email" => "Kristin.Rolfson@madelyn.tv",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Leuschke",
                    "first_name" => "Estelle",
                    "nationality" => "Niue",
                    "email" => "Chauncey.Hoeger@jeramie.tv",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Funk",
                    "first_name" => "Roselyn",
                    "nationality" => "Djibouti",
                    "email" => "Korbin@hallie.io",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Romaguera",
                    "first_name" => "Kariane",
                    "nationality" => "Djibouti",
                    "email" => "Jocelyn_Fadel@lauryn.com",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Nitzsche",
                    "first_name" => "Adrian",
                    "nationality" => "Guernsey",
                    "email" => "Markus.Gulgowski@nicolas.tv",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Windler",
                    "first_name" => "Maggie",
                    "nationality" => "Guernsey",
                    "email" => "Shayna.Lesch@donny.io",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Blanda",
                    "first_name" => "Ken",
                    "nationality" => "French Southern Territories",
                    "email" => "Modesta_Aufderhar@belle.co.uk",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Reilly",
                    "first_name" => "Antone",
                    "nationality" => "Yemen",
                    "email" => "Ford@garfield.name",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Cassin",
                    "first_name" => "Yadira",
                    "nationality" => "Mayotte",
                    "email" => "Anastacio@murray.net",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Macejkovic",
                    "first_name" => "Marge",
                    "nationality" => "Slovakia",
                    "email" => "Retha@griffin.me",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Feest",
                    "first_name" => "Rogers",
                    "nationality" => "Monaco",
                    "email" => "Keshawn_Kuvalis@orlando.name",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Fadel",
                    "first_name" => "Candelario",
                    "nationality" => "Belarus",
                    "email" => "Kailee_Casper@reina.me",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Shields",
                    "first_name" => "Eldridge",
                    "nationality" => "Neutral Zone",
                    "email" => "Rachel_Block@olin.info",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Romaguera",
                    "first_name" => "Lavina",
                    "nationality" => "Canton and Enderbury Islands",
                    "email" => "Cathrine@virgie.us",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Hessel",
                    "first_name" => "Matt",
                    "nationality" => "Czech Republic",
                    "email" => "Skyla@gonzalo.net",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Donnelly",
                    "first_name" => "Barrett",
                    "nationality" => "South Korea",
                    "email" => "Sheila.Abshire@david.io",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Hagenes",
                    "first_name" => "Betty",
                    "nationality" => "Samoa",
                    "email" => "Linda@monte.me",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Schmeler",
                    "first_name" => "Alphonso",
                    "nationality" => "Palau",
                    "email" => "Raphael_Senger@vernon.biz",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Shields",
                    "first_name" => "Selmer",
                    "nationality" => "Samoa",
                    "email" => "Michelle.Rice@pat.me",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Kemmer",
                    "first_name" => "Earl",
                    "nationality" => "Niger",
                    "email" => "Terry.Rau@brennan.com",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Kunde",
                    "first_name" => "Sharon",
                    "nationality" => "French Guiana",
                    "email" => "Julius@isabell.io",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Jacobs",
                    "first_name" => "Jeffry",
                    "nationality" => "Albania",
                    "email" => "Juliana.Stanton@magnolia.ca",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Ritchie",
                    "first_name" => "Eliane",
                    "nationality" => "Chad",
                    "email" => "Kaleigh.Durgan@verner.us",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Erdman",
                    "first_name" => "Howard",
                    "nationality" => "Puerto Rico",
                    "email" => "Arthur_Stroman@quinn.com",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Schimmel",
                    "first_name" => "Lance",
                    "nationality" => "Serbia",
                    "email" => "Dovie.Williamson@alycia.org",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Tillman",
                    "first_name" => "Elliott",
                    "nationality" => "Botswana",
                    "email" => "Bethel@jess.com",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Boyle",
                    "first_name" => "Emanuel",
                    "nationality" => "Tokelau",
                    "email" => "Claude@brent.us",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Feest",
                    "first_name" => "Norma",
                    "nationality" => "Georgia",
                    "email" => "Abdullah.Terry@leonardo.net",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "O'Conner",
                    "first_name" => "Jenifer",
                    "nationality" => "Nepal",
                    "email" => "Virgie@robert.name",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Towne",
                    "first_name" => "Lilliana",
                    "nationality" => "New Caledonia",
                    "email" => "Henri@breana.org",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Padberg",
                    "first_name" => "Verner",
                    "nationality" => "Seychelles",
                    "email" => "Florencio@barney.com",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Stiedemann",
                    "first_name" => "Adelia",
                    "nationality" => "Greece",
                    "email" => "Jessika.Nader@glennie.name",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Turcotte",
                    "first_name" => "Tristin",
                    "nationality" => "Nauru",
                    "email" => "Joyce_Jaskolski@emmalee.name",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Pouros",
                    "first_name" => "Cooper",
                    "nationality" => "Micronesia",
                    "email" => "Chase_Kub@emely.us",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Romaguera",
                    "first_name" => "Judy",
                    "nationality" => "Australia",
                    "email" => "Charlotte@earl.info",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Tremblay",
                    "first_name" => "Maxie",
                    "nationality" => "French Guiana",
                    "email" => "Annamae.Upton@roma.biz",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Barrows",
                    "first_name" => "Akeem",
                    "nationality" => "Mozambique",
                    "email" => "Wellington@mara.ca",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Funk",
                    "first_name" => "Florencio",
                    "nationality" => "Malawi",
                    "email" => "Kenna@vicky.us",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Welch",
                    "first_name" => "Margarita",
                    "nationality" => "Ethiopia",
                    "email" => "Wellington_Cormier@novella.tv",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Legros",
                    "first_name" => "Helmer",
                    "nationality" => "Antigua and Barbuda",
                    "email" => "Ubaldo@bessie.us",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Labadie",
                    "first_name" => "Carole",
                    "nationality" => "Martinique",
                    "email" => "Josh@kelvin.io",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Klein",
                    "first_name" => "Desiree",
                    "nationality" => "Nepal",
                    "email" => "Isidro_Homenick@jerald.biz",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Kuvalis",
                    "first_name" => "Eloy",
                    "nationality" => "Panama Canal Zone",
                    "email" => "Annabelle_Okuneva@christelle.com",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Macejkovic",
                    "first_name" => "Lucinda",
                    "nationality" => "Austria",
                    "email" => "Ada_Wuckert@kirk.us",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
                [
                    "surname" => "Bosco",
                    "first_name" => "Emilia",
                    "nationality" => "São Tomé and Príncipe",
                    "email" => "Yasmin@darwin.us",
                    "address_id" => rand(0, 88),
//                    "course_id" => rand(0, 199),
                ],
            ];

            foreach ($students as $student) {
                Student::create($student);
            }
        }
    }
}
